spring:
  datasource:
    url: jdbc:h2:mem:document-service-db
    username: sa
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false