spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - ${FRONTEND_ORIGIN}
            allowed-headers:
              - content-type
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE

server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
