name: Java Checkstyle

on: [pull_request]

jobs:
  checkstyle:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@0.6.0
        with:
          reporter: 'github-pr-check'
          checkstyle_config: checkstyle.xml